### ISSUE TITLE
docs: PDF documentation broken

### ISSUE THREAD

**Issue by jdeamicis** [canonical/ubuntu-packaging-guide#58] opened 2024-06-26 16:54 UTC
I can't seem to be able to download the PDF documentation generated by read-the-docs. The browser doesn't open the file, and when I try to download it directly, my PDF reader says it's corrupted.

---
*Reported from: https://canonical-ubuntu-packaging-guide.readthedocs-hosted.com/en/latest/*

**Comment by dviererbe** [comment] 2024-06-27 08:44
Thanks for bringing this to our attention!

I can confirm this issue:
- on Ubuntu the Document Viewer reports that the PDF file is damaged
- and Firefox just loads forever

As a workaround for everyone that needs to work with the Ubuntu Packaging Guide in an offline environment I can recommend installing the [Snap](https://snapcraft.io/ubuntu-packaging-guide) that serves the documentation from a locally hosted web server.

**Comment by dviererbe** [comment] 2024-06-27 09:08
Running `make latexpdf` does not work at all :/

```plain
make -C docs latexpdf
make[1]: Entering directory '/home/dviererbe/Repositories/Canonical/ubuntu-packaging-guide/docs'
. .sphinx/venv/bin/activate; sphinx-build -M latexpdf "." "_build" -c . -d .sphinx/.doctrees 
Running Sphinx v7.3.7
matplotlib is not installed, social cards will not be generated
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [latex]: all documents
updating environment: 0 added, 0 changed, 0 removed
reading sources... 
looking for now-outdated files... none found
copying TeX support files... copying TeX support files...
done
processing ubuntu-packaging-guide.tex... index tutorial tutorial/getting-set-up tutorial/make-changes-to-package tutorial/create-new-package tutorial/fix-bug how-to how-to/get-package-source how-to/download-new-upstream-version how-to/build-packages how-to/install-built-packages how-to/run-tests how-to/upload-packages-to-ppa how-to/write-patchfiles how-to/propose-changes how-to/use-schroots explanation explanation/upstream-and-downstream explanation/package-model explanation/development-process explanation/releases explanation/archive explanation/launchpad explanation/sponsoring explanation/proposed-migrations explanation/stable-release-updates explanation/debian-syncs explanation/debian-merges explanation/transitions explanation/backports explanation/main-inclusion-review reference reference/debian-dir-overview reference/architectures reference/package-tests reference/package-version-format reference/git-ubuntu reference/apt reference/debian-policy reference/filesystem-hierarchy-standard reference/outdated-tools reference/launchpad-text-markup reference/glossary contribute 
resolving references...
done
writing... done
copying images... [100%] images/reference/glossary/Old-Ubuntu-Login-Background.jpg
build succeeded.

The LaTeX files are in _build/latex.
Run 'make' in that directory to run these through (pdf)latex
(use `make latexpdf' here to do that automatically).
make[2]: Entering directory '/home/dviererbe/Repositories/Canonical/ubuntu-packaging-guide/docs/_build/latex'
latexmk -pdf -dvi- -ps-  'ubuntu-packaging-guide.tex'
make[2]: latexmk: No such file or directory
make[2]: *** [Makefile:29: ubuntu-packaging-guide.pdf] Error 127
make[2]: Leaving directory '/home/dviererbe/Repositories/Canonical/ubuntu-packaging-guide/docs/_build/latex'
make[1]: *** [Makefile:105: latexpdf] Error 2
make[1]: Leaving directory '/home/dviererbe/Repositories/Canonical/ubuntu-packaging-guide/docs'
make: *** [Makefile:5: latexpdf] Error 2
```

To set expectations: **I will wait to work on solving this until the new Sphinx Extension at [canonical/sphinx-docs-starter-pack](https://github.com/canonical/sphinx-docs-starter-pack) has been landed**, because when we migrate it will change the configuration files fundamentally.

**Comment by dviererbe** [comment] 2024-06-27 14:06
@s-makin told me that someone fixed the PDF issue for a documentation project from the Ubuntu Server team. I still recommend waiting to fix this until we migrated to the new sphinx extension to avoid potential duplicate work.

**Comment by dviererbe** [comment] 2024-07-02 12:04
@SecondSkoll if it is not a lot of work than you are very welcome to open PR to fix PDF building :)

**Comment by SecondSkoll** [comment] 2024-07-10 06:29
This should be solved with #61

**Comment by dviererbe** [comment] 2024-07-10 06:37
@SecondSkoll downloading a PDF via ReadTheDocs still does not work

**Comment by SecondSkoll** [comment] 2024-07-10 07:35
Oh dear. Yes, it seems that it's a pathing issue.

`$READTHEDOCS_OUTPUT` defaults to `_readthedocs/`, which then builds in `_readthedocs/<format>` directories. As this is a root directory the paths to the local paths to the files used for PDF generation break.

I'll have to see how this can be solved with a general solution. It could likely be solved by setting `$READTHEDOCS_OUTPUT` to the `docs/` directory in a `pre_install` step in the `.readthedocs.yaml` file, but I'll prepare a proper test and submit a new PR tomorrow (it's a bit late for me, sorry).

**Comment by SecondSkoll** [comment] 2024-07-11 03:53
#64 should actually solve this issue. Let me know if you have any problems with it! :)

**Closed** 2024-07-11 07:30 UTC
Labels: bug
